apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    - name: debug
      image: centos:7
      imagePullPolicy: IfNotPresent
      command:
        - "sh"
        - "-c"
      args:
        - |
          while true
          do
            sleep 5
          done
